name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-2022

    steps:
      - name: Install GTK4 (Windows)
        run: |
          pipx install gvsbuild
          gvsbuild build gtk4 librsvg
