name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-2022

    steps:
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.13' 
      - name: Install GTK4 (Windows)
        run: |
          pipx install gvsbuild --python "3.13"
          gvsbuild build gtk4 librsvg
